debug: false
spring:
   application:
      name: batch-toolbox
   datasource:
      type: org.springframework.jdbc.datasource.SimpleDriverDataSource
      url: jdbc:postgresql://localhost:5432/batch-patterns
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: admin
   batch:
      job:
         enabled: false
logging:
   level:
      root: info
      org.springframework.batch: info
      org.springframework.boot.autoconfigure.batch: debug