INSERT into BATCH_JOB_INSTANCE (JOB_INSTANCE_ID,VERSION,JOB_NAME,JOB_KEY)
values (-101,0,'jobTest','be310a80201b313039ac64ba1dd90d9f');

INSERT into BATCH_JOB_EXECUTION (JOB_EXECUTION_ID,VERSION,JOB_INSTANCE_ID,CREATE_TIME,START_TIME,END_TIME,STATUS,EXIT_CODE,EXIT_MESSAGE,LAST_UPDATED)
values (-1,1,-101,TIMESTAMP '2021-05-01', TIMESTAMP '2021-05-01', NULL,'STARTED','UNKNOWN',null,CURRENT_TIMESTAMP);

INSERT into BATCH_JOB_EXECUTION_CONTEXT (JOB_EXECUTION_ID,SHORT_CONTEXT)
values (-1,'{"@class":"java.util.HashMap"}');


